name: scoutboard
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http: ^0.12.0+4
  fluttertoast: ^3.1.0
  intl: ^0.15.7
  flutter_slidable: "^0.5.4"
  grouped_list: ^2.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  table_calendar: ^2.2.3
  flutter_rating_bar: ^3.0.1+1
  percent_indicator: ^2.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/sb.png
    - assets/images/stars-5.png
    - assets/images/stars-5-2.png
    - assets/images/stars-5-3.png
    - assets/images/stars-5-4.png
    - assets/images/158335311763927743.png
    - assets/images/group-2.png
    - assets/images/group-2-2.png
    - assets/images/union-7.png
    - assets/images/union-43.png
    - assets/images/bg-3.png
    - assets/images/backward-arrow.png
    - assets/images/backward-arrow-2.png
    - assets/images/backward-arrow-4.png
    - assets/images/dropbox.png
    - assets/images/icon-calendar.png
    - assets/images/icon-customers.png
    - assets/images/icon-dashboard.png
    - assets/images/icon-invoices.png
    - assets/images/icon-products.png
    - assets/images/icon-setting.png
    - assets/images/icon-sales.png
    - assets/images/path-3149.png
    - assets/images/path-3149-2.png
    - assets/images/path-3150.png
    - assets/images/path-3150-2.png
    - assets/images/path-3151.png
    - assets/images/path-3152.png
    - assets/images/path-3157.png
    - assets/images/path-3161.png
    - assets/images/path-3163.png
    - assets/images/sidebarbg.png
    - assets/images/sidebarbg-2.png
    - assets/images/symbol-156--1.png
    - assets/images/login_background.png
    - assets/images/registration_background.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: SourceSansPro
       fonts:
         - asset: assets/fonts/SourceSansPro-Regular.ttf
         - asset: assets/fonts/SourceSansPro-Bold.ttf
           weight: 700
     - family: Ubuntu
       fonts:
         - asset: assets/fonts/Ubuntu-L.ttf
           weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
